[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bstr = "1.12.1"
env_logger = "0.11.8"
gen-combinations = "0.1.0"
ilog = "1.0.1"
log = "0.4.29"
ndarray = "0.17.1"
prime_factorization = "1.0.5"
regex = "1.12.2"
